#!/bin/sh

set -e

TMP1=$(mktemp)
TMP2=$(mktemp)
TMP3=$(mktemp)

objdump -t ../../output/kernel.bin | sed '/\bd\b/d' | sort > "$TMP1"
grep "\.text" < "$TMP1" | cut -d' ' -f1 > "$TMP2"
grep "\.text" < "$TMP1" | awk 'NF{ print $NF }' > "$TMP3"

cat <<EOF >_symbols.gen
//
// AUTO GENERATED FILE.
// DO NOT EDIT THIS FILE.
//

#include <kernel/symbols.h>

const symbol_t _KernelSymbols[] = {
EOF

paste -d'$' "$TMP2" "$TMP3" | sed 's/^/    { .addr = 0x/g' | sed 's/\$/, .name = "/g' | sed 's/$/"},/g' >> _symbols.gen

cat <<EOF >> _symbols.gen
    { .addr = 0xffffffffffffffff, .name = ""}
};
EOF

rm -rf "$TMP1" "$TMP2" "$TMP3"
